-- Operations analytics daily report.

CREATE TABLE IF NOT EXISTS `operation_daily_report` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `report_date` DATE NOT NULL COMMENT 'Report date, one report per day',
    `title` VARCHAR(200) NOT NULL DEFAULT '运营日报' COMMENT 'Report title',
    `summary` LONGTEXT NULL COMMENT 'LLM or fallback summary',
    `sections_json` JSON NULL COMMENT 'Per-section query results, charts and insights',
    `anomalies_json` JSON NULL COMMENT 'Governed anomaly detection findings',
    `suggestions_json` JSON NULL COMMENT 'Action suggestions',
    `llm_generated` TINYINT NOT NULL DEFAULT 0 COMMENT '1 when summary was generated by the LLM',
    `status` VARCHAR(20) NOT NULL DEFAULT 'SUCCESS' COMMENT 'SUCCESS/FAILED',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_report_date` (`report_date`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Operations analytics daily report';
