CREATE TABLE IF NOT EXISTS `operation_action` (
    `id` CHAR(36) NOT NULL,
    `finding_id` CHAR(36) NULL,
    `action_type` VARCHAR(32) NOT NULL,
    `target_type` VARCHAR(64) NOT NULL,
    `target_id` VARCHAR(128) NOT NULL,
    `reason` TEXT NOT NULL,
    `proposed_payload_json` JSON NOT NULL,
    `payload_hash` CHAR(64) NOT NULL,
    `payload_schema_version` VARCHAR(32) NOT NULL DEFAULT 'v1',
    `evidence_json` JSON NULL,
    `risk_level` VARCHAR(16) NOT NULL,
    `approval_required` TINYINT NOT NULL DEFAULT 1,
    `status` VARCHAR(32) NOT NULL,
    `idempotency_key` VARCHAR(128) NOT NULL,
    `created_by` BIGINT NULL,
    `approved_by` BIGINT NULL,
    `approved_at` DATETIME NULL,
    `rejection_reason` VARCHAR(500) NULL,
    `executed_by` BIGINT NULL,
    `execution_json` JSON NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `executed_at` DATETIME NULL,
    `expires_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_operation_action_idempotency` (`idempotency_key`),
    INDEX `idx_operation_action_status_created` (`status`, `created_at`),
    INDEX `idx_operation_action_target` (`target_type`, `target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Auditable operation action proposals';
